import { Product } from "./dulces";

export const data:Product []=[

    {
    id_dulce:	1,
    img:	"/images/dulces/carlosv.png",
    nombre:	"Carlos V",
    descripcion:	"Chocolate macizo en barra 20g",
    marca:	"Nestlé",
    sku:	"chcv20",
    precio:	109,
    categoria:	"chocolates",
    impuestos:	"8%",
    contCaja:	24,
    contDisplay:	20
    },

    {
    id_dulce:	2,
    img:	"/images/dulces/kisses.png",  
    nombre:	"Kisses",
    descripcion:	"Barra de chocolate de leche macizo con almendras tostadas",
    marca:	"Hersheys",
    sku:	"kich15",
    precio:	269, 
    categoria: "chocolates",
    impuestos:	" 8%",
    contCaja:	24, 
    contDisplay:	12, 
    },

    {
    id_dulce:	3,
    img:	"/images/dulces/hersheys.png", 
    nombre:	"Chocolate con almendras",
    descripcion:	"Chocolates de leche macizo con almendras en barra",
    marca:	"Hersheys",
    sku:	"almhersh1",
    precio:	106,
    categoria:	"chocolates",
    impuestos:	"8%",
    contCaja:	12,
    contDisplay:	16, 
    },     

    {
    id_dulce:	4, 
    img:	"/images/dulces/bocadin.png",
    nombre:	"Bocadin",
    descripcion:	" Chocolate cremoso con galleta waffle cubierto de chocolate",
    marca:	"Ricolino",
    sku:	"bocric1",
    precio:	98,
    categoria:	"chocolates",
    impuestos:	"8%",
    contCaja:	12,
    contDisplay:	50, 
    }, 

    {
    id_dulce:	5,
    img:	"/images/dulces/totis.png",
    nombre:	"Totis Limón y sal",
    descripcion:	"Botana de trigo sabor limón y sal en sobre de 10g",
    marca:	" Totis",
    sku:	"totlim10",
    precio:	149,
    categoria:	"botanas y salsas",
    impuestos:	"16%",
    contCaja:	6,
    contDisplay:	25, 
    }, 

    {
    id_dulce:	6,
    img:	"/images/dulces/conchitas.png",
    nombre:	"Conchitas con sal",
    descripcion:	"Fritura de maíz sazonada conchitas con sal sobre 15g",
    marca:	"Encanto",
    sku:	"conchlim15",
    precio:	219, 
    categoria:	"botanas y salsas",
    impuestos:	"16%",
    contCaja:	12, 
    contDisplay:	12, 
    }, 

    {
    id_dulce:	7,
    img:	"/images/dulces/ruffles.png",
    nombre:	"Ruffles sabor queso",
    descripcion:	"Botana sabor queso en sobre 67g",
    marca:	"Sabritas",
    sku:	"ruffqu67",
    precio:	298,
    categoria:	"botanas y salsas",
    impuestos:	"16%",
    contCaja:	 4,
    contDisplay:	20, 
    }, 

    {
    id_dulce:	8,
    img:	"/images/dulces/cheetos.png",
    nombre:	"Cheetos sabor queso",
    descripcion:	"Fritura sabor queso y chile en sobre 55g",
    marca:	"Sabritas",
    sku:	"heeque55",
    precio:	319,
    categoria:	"botanas y salsas",
    impuestos:	"6%",
    contCaja:	4,
    contDisplay:	20,
    }, 

    {
    id_dulce:	9,
    img:	"/images/dulces/rellerindos.png",
    nombre:	"Rellerindos Tamarindo",
    descripcion:	"Caramelo macizo acidulado sabor tamarindo relleno de pulpa picosita",
    marca:	"Vero",
    sku:	"relletam6",
    precio:	98,
    categoria:	"aciditos y picositos",
    impuestos:	"8%",
    contCaja:	20,
    contDisplay:	30 , 
    }, 

    {
    id_dulce:	10, 
    img:	"/images/dulces/skwinkles.png",
    nombre:	"Skwinkles rellenos", 
    descripcion:	"Dulce enchilado en tiras sabor mango relleno pulpa sabor sandia", 
    marca:	"Mars", 
    sku:	"skwrellsan", 
    precio:	139, 
    categoria:	"aciditos y picositos", 
    impuestos:	"8%", 
    contCaja:	18,
    contDisplay:	12, 
    }, 

    {
    id_dulce: 	11,
    img:	"/images/dulces/pelon.png",
    nombre:	"Pelón Rico",
    descripcion:	"Dulce enchilado de pulpa sabor amarindo 15g",
    marca:	"De la Rosa",
    sku:	"peltam10",
    precio:	190,
    categoria:	"aciditos y picositos",
    impuestos:	"8%",
    contCaja:	16,
    contDisplay:	36, 
    }, 

    {
    id_dulce:	12,
    img:	"/images/dulces/tamaroca.png",
    nombre:	"Tama-Roca Pellizco",
    descripcion:	"Tamarindo natural con sal y chile15g",
    marca:	"Tama-Roca",
    sku:	"tampell15",
    precio:	215,
    categoria:	"aciditos y picositos",
    impuestos:	" 8%",
    contCaja:	16,
    contDisplay:	40, 

    }, 

    {
    id_dulce:	13,
    img:	"/images/dulces/orbit.png",
    nombre:	"Orbit 4's Menta", 
    descripcion:	"Goma de mascar sabor menta sin azúcar", 
    marca:	"Wrigleys", 
    sku:	"orb4smen", 
    precio:	75,
    categoria:	"chicles", 
    impuestos:	"16%", 
    contCaja:	12,
    contDisplay:	40
    }, 

    {
    id_dulce:	14,
    img:	"/images/dulces/canels.png",
    nombre:	"Canel's 4's",
    descripcion:	"Goma de mascar sabor violeta",
    marca:	"Canel's",
    sku:	"canelTu75",
    precio:	139,
    categoria:	"chicles",
    impuestos:	"16%",
    contCaja:	20, 
    contDisplay:	60
    }, 

    {
    id_dulce:	15, 
    img:	"/images/dulces/trident.png",
    nombre:	"Trident menta fresca", 
    descripcion:	"Goma de mascar sabor menta paquete 18 tiras", 
    marca:	"Trident", 
    sku:	"trimen18", 
    precio:	282,
    categoria:	"chicles", 
    impuestos:	"16%", 
    contCaja:	16,
    contDisplay:	20
    }, 

    {
    id_dulce:	16,
    img:	"/images/dulces/bubbaloo.png",
    nombre:	"Bubbaloo fresa",
    descripcion:	"Goma de mascar sabor fresa 2g",
    marca:	"Sonrics",
    sku:	"bubbfres2",
    precio:	235,
    categoria:	"chicles",
    impuestos:	"16%",
    contCaja:	16,
    contDisplay:	70
    }, 

    {
    id_dulce:	17,
    img:	"/images/dulces/rokaleta.png",
    nombre:	"Rockaleta",
    descripcion:	"Paleta de dulce sabores varios y cubierta picosita",
    marca:	"Sonrics",
    sku:	"rokale18",
    precio:	98, 
    categoria:	"paletas",
    impuestos:	"16%",
    contCaja:	20,
    contDisplay:	18
    }, 

    {
    id_dulce:	18,
    img:	"/images/dulces/tarrito.png",
    nombre:	"Tarrito",
    descripcion:	"Paleta de dulce macizo sabor piña crema 16 g,", 
    marca:	"Vero", 
    sku:	"tarri40", 
    precio:	89,
    categoria:	"paletas", 
    impuestos:	"16%",
    contCaja:	16,
    contDisplay:	40
    }, 

    {
    id_dulce:	19,
    img:	"/images/dulces/chupachups.png",
    nombre:	"Chupa Chups Cremosa", 
    descripcion:	"Paleta de dulce macizo sabor vainilla fresa chocolate y crema 14 g", 
    marca:	"Sonrics", 
    sku:	"chupcre14", 
    precio:	84,
    categoria:	"paletas", 
    impuestos:	"16%", 
    contCaja:	16,
    contDisplay:	40, 
    }, 

    {
    id_dulce:	20,
    img:	"/images/dulces/verofuego.png",
    nombre:	"Vero Mix paleta Fuego",
    descripcion:	"Paleta de dulce macizo sabor surtido Elotes Mango Sandia 14 g",
    marca:	"Vero",
    sku:	"mixvero14",
    precio:	68,
    categoria:	"paletas",
    impuestos:	"16%",
    contCaja:	18,
    contDisplay:	20, 
    }

    ]